# Generated by Django 4.2.5 on 2023-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_id_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_poste',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
