# Generated by Django 4.2.5 on 2023-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_id_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(choices=[('jovena', 'Jovena'), ('prestataire', 'Prestataire'), ('station_service', 'Station_service'), ('transporteur', 'Transporteur')], default=None, max_length=50, null=True),
        ),
    ]
