# Generated by Django 4.2.5 on 2023-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_jov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_jov', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='document_prest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_prest', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='document_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_stat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='document_trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_trans', models.TextField()),
            ],
        ),
    ]
