# Generated by Django 4.2.5 on 2023-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_document_jov_document_prest_document_stat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostic',
            fields=[
                ('num_reclamation', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('panne_annoncee', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('localite', models.CharField(max_length=200)),
                ('entreprise_intervenante', models.CharField(max_length=200)),
                ('categorie_reclamation', models.CharField(max_length=200)),
                ('date_reclamation', models.DateField(auto_now_add=True)),
                ('echeance', models.DateField()),
                ('date_diagnostic', models.DateTimeField(auto_now_add=True)),
                ('interlocuteur', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('panne_reel', models.CharField(max_length=200)),
            ],
        ),
    ]
