# Generated by Django 4.2.5 on 2023-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_diagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesure_de_securite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_specifique', models.BooleanField(default=False)),
                ('information_personnel', models.BooleanField(default=False)),
                ('port_EPI', models.BooleanField(default=True)),
                ('balisage_perimetre', models.BooleanField(default=False)),
                ('extincteur_adapte', models.BooleanField(default=False)),
                ('interdiction_de_fumer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='nature_risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_gaz', models.BooleanField(default=False)),
                ('incendie', models.BooleanField(default=False)),
                ('explosion', models.BooleanField(default=False)),
                ('projection_etincelle', models.BooleanField(default=False)),
                ('intoxication', models.BooleanField(default=False)),
                ('asphyxie', models.BooleanField(default=False)),
                ('brulure', models.BooleanField(default=False)),
                ('blessure', models.BooleanField(default=False)),
                ('chute_plain_pied', models.BooleanField(default=False)),
                ('chute_objet', models.BooleanField(default=False)),
                ('chute_hauteur', models.BooleanField(default=False)),
                ('incident_reseau', models.BooleanField(default=False)),
                ('epandage', models.BooleanField(default=False)),
                ('eboulement', models.BooleanField(default=False)),
                ('electrocution', models.BooleanField(default=False)),
                ('incident_cable', models.BooleanField(default=False)),
                ('accident_circulation', models.BooleanField(default=False)),
                ('autre_lesion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='risque_interference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison_carburant', models.DateField()),
                ('presence_zone', models.CharField(max_length=200)),
                ('autre_travaux', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='date_diagnostic',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='num_reclamation',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
