# Generated by Django 4.2.5 on 2023-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mesure_de_securite_nature_risque_risque_interference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mesure_de_securite',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='balisage_perimetre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='extincteur_adapte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='information_personnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='interdiction_de_fumer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='permis_specifique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='port_EPI',
            field=models.BooleanField(default=True),
        ),
    ]
