# Generated by Django 4.2.5 on 2023-10-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_mesure_de_securite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diagnostic',
            new_name='Checklist_jov',
        ),
    ]
