# Generated by Django 4.2.5 on 2023-10-03 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_diagnostic_checklist_jov'),
    ]

    operations = [
        migrations.DeleteModel(
            name='risque_interference',
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='autre_travaux',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='livraison_carburant',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='presence_zone',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='checklist_jov',
            name='date_diagnostic',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
