# Generated by Django 4.2.5 on 2023-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_risque_interference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_jov',
            name='autre_nature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='chauffage_soudage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='deplacement_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='fouille_mannuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='grenaillage_sablage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='manutention_levage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='operation_piste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='percage_moulage_decoupage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_chaud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_engin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_equipement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_espace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_hauteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travail_tuyauterie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travaux_bruyant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travaux_demolition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='travaux_excavation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='utilisation_equipement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_jov',
            name='vidange_degazage',
            field=models.BooleanField(default=False),
        ),
    ]
