# Generated by Django 4.2.5 on 2023-10-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_checklist_jov_autre_nature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_jov',
            name='autre_nature',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='chauffage_soudage',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='deplacement_site',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='fouille_mannuelle',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='grenaillage_sablage',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='manutention_levage',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='operation_piste',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='percage_moulage_decoupage',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_chaud',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_engin',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_equipement',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_espace',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_hauteur',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travail_tuyauterie',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travaux_bruyant',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travaux_demolition',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='travaux_excavation',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='utilisation_equipement',
        ),
        migrations.RemoveField(
            model_name='checklist_jov',
            name='vidange_degazage',
        ),
    ]
