# Generated by Django 4.2.5 on 2023-10-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_checklist_jov_autre_nature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist_jov',
            new_name='Checklist_stat',
        ),
    ]
