# Generated by Django 4.2.5 on 2023-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_checklist_stat_accident_circulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_permis_feu_prest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entete', models.DateField(auto_now_add=True)),
                ('registre_entete', models.IntegerField()),
                ('site', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('localite', models.CharField(max_length=200)),
                ('entreprise_intervenante', models.CharField(max_length=200)),
                ('descriptif_travail', models.CharField(max_length=200)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('heure_debut', models.TimeField(auto_now_add=True)),
                ('heure_fin', models.TimeField(auto_now_add=True)),
                ('date_fin', models.DateField(auto_now_add=True)),
                ('proximite_zone_ATEX', models.BooleanField(default=False)),
                ('autre_risque', models.CharField(max_length=50)),
                ('intervenant1', models.CharField(max_length=50)),
                ('intervenant2', models.CharField(max_length=50)),
                ('intervenant3', models.CharField(max_length=50)),
                ('intervenant4', models.CharField(max_length=50)),
                ('soudage', models.BooleanField(default=False)),
                ('tronconnage', models.BooleanField(default=False)),
                ('decoupage', models.BooleanField(default=False)),
                ('meulage', models.BooleanField(default=False)),
                ('autre_type_travaux', models.CharField(max_length=50)),
                ('poste_souder', models.BooleanField(default=False)),
                ('chalumeau', models.BooleanField(default=False)),
                ('meuleuse', models.BooleanField(default=False)),
                ('tronconneuse', models.BooleanField(default=False)),
                ('autre_materiel_utilise', models.CharField(max_length=50)),
                ('plan_prevention', models.BooleanField(default=False)),
                ('ASET', models.BooleanField(default=False)),
                ('permis_entree_espace_confine', models.BooleanField(default=False)),
                ('autre_document', models.CharField(max_length=50)),
                ('evacuation_substance', models.BooleanField(default=False)),
            ],
        ),
    ]
