# Generated by Django 4.2.5 on 2023-10-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_checklist_permis_feu_prest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='evacuation_substance',
        ),
    ]
