# Generated by Django 4.2.5 on 2023-10-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_checklist_permis_feu_prest_bache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='bache',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='consignation_equipement',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='degazage',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='demontage_tuyauterie',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='ecran',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='extincteur',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='isolation_tuyauterie',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='protection_element',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='sable',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='teneur_LIE',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='teneur_oxygene',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='test_atmospherique',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='ventilation',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='vidange',
        ),
    ]
