# Generated by Django 4.2.5 on 2023-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_checklist_permis_feu_prest_bache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='bache',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='consignation_equipement',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='degazage',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='demontage_tuyauterie',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='ecran',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='extincteur',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='isolation_tuyauterie',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='protection_element',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='sable',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='teneur_LIE',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='teneur_oxygene',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='test_atmospherique',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='ventilation',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='vidange',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
