# Generated by Django 4.2.5 on 2023-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_checklist_permis_feu_prest_bache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_excavation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entete', models.DateField(auto_now_add=True)),
                ('Registre_entete', models.IntegerField()),
                ('site', models.CharField(max_length=50)),
                ('localite', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=50)),
                ('entreprise_intervenante', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
                ('profondeur_excavation', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
    ]
