# Generated by Django 4.2.5 on 2023-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_checklist_excavation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_excavation',
            name='type_excavation',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
