# Generated by Django 4.2.5 on 2023-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_checklist_excavation_type_excavation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_excavation',
            name='type_excavation',
            field=models.CharField(max_length=10),
        ),
    ]
