# Generated by Django 4.2.5 on 2023-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_checklist_excavation_type_excavation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_excavation',
            name='atre_obstruction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='cable_cathodique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='cable_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction1',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction2',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction3',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction4',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction5',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire_obstruction6',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='dessin1',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='dessin2',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='dessin3',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='dessin4',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='eau_domestique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='eau_incendie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='eau_pluviale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='eau_riviere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='effluent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='electrique_11kv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='electrique_690i',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='electrique_690v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='electrique_6kv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='ligne_gaz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='mise_terre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='sanitaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='structure_adjacente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklist_excavation',
            name='descriptif',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
