# Generated by Django 4.2.5 on 2023-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_checklist_excavation_atre_obstruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_excavation',
            name='banc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire1',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire2',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire3',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='commentaire4',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='etayage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='fermeture_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='mesure_securite_additionnel',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='pente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='permis_espace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='pompage_eau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='pretection_nuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='pretection_ouverture',
            field=models.BooleanField(default=False),
        ),
    ]
