# Generated by Django 4.2.5 on 2023-10-06 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_checklist_excavation_banc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_excavation',
            name='date_achevement_excavation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='effectuee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='effectuer_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='effectuer_nom',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='permis_excavation_delivre',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='representant_contracant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='representant_contracant_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='representant_contracant_nom',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='representant_proprietaire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='representant_proprietaire_nom',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='superviseur_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='superviseur_excavation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='superviseur_excavation_nom',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='superviseur_nom',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
