# Generated by Django 4.2.5 on 2023-10-06 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_checklist_excavation_date_achevement_excavation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_espace_confine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entete', models.DateField(default=datetime.date.today)),
                ('registre_entete', models.IntegerField()),
            ],
        ),
    ]
