# Generated by Django 4.2.5 on 2023-10-06 06:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_checklist_espace_confine'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='date_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='descriptif_travail',
            field=models.CharField(default='N\\A', max_length=50, verbose_name='Essai'),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='entreprise_intervenante',
            field=models.CharField(default='N\\A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='equipement',
            field=models.CharField(default='N\\A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='heure_debut',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='heure_fin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='site',
            field=models.CharField(default='N\\A', max_length=200),
        ),
    ]
