# Generated by Django 4.2.5 on 2023-10-06 08:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_checklist_espace_confine_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='ASET',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='Co_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='H2S_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='LIE_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='NH3_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='SO_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='alerte',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='ambulance',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='appareil_respiratoire_autonome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='appareil_respiratoire_isolant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='autre_intervention',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='balisage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='consignation_electique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='consignation_fluidique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='consignation_mecanique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='corde_assurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='date_heure1',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='date_heure2',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='date_heure3',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='detecteur_gaz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='harnais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='masque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='moyen_intervenant',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='nom_cloture',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Nom du responsable habilité'),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='nom_reponsable_jovena',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='nom_surveillant',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Nom du surveillant'),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='nom_testeur',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Nom du testeur de Gaz'),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_PPM1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_PPM2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_PPM3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_heure1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_heure2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='o2_heure3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='panneaux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='permi_delivre',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='plan_urgence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='pompier',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='responsable_jovena',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='responsable_site',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='treuil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='ventilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='ventilation_forcee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklist_espace_confine',
            name='descriptif_travail',
            field=models.CharField(default='N\\A', max_length=50, verbose_name='Descriptif du travail'),
        ),
    ]
