# Generated by Django 4.2.5 on 2023-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_checklist_espace_confine_aset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_appareil_respiratoire_autonome',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_appareil_respiratoire_isolant',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_balisage',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_corde_assurance',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_detecteur_gaz',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_harnais',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_masque',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_panneaux',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='type_treuil',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
