# Generated by Django 4.2.5 on 2023-10-10 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_checklist_espace_confine_type_appareil_respiratoire_autonome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='alerte',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut_surveillance',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin_surveillance',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_responsable_HSE',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_responsable_autre',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_responsable_site',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_responsable_travaux',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_surveillance_apres',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='nom_surveillance_pendant',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='numero_ambulance',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='numero_jovena',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='numero_pompier',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='numero_site',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='permis_feu_delivre',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='qualite_responsable_HSE',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='qualite_responsable_autre',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='qualite_responsable_site',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='qualite_responsable_travaux',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='visa_responsable_HSE',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='visa_responsable_autre',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='visa_responsable_site',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='visa_responsable_travaux',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='autre_instruction',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='date_heure_site_intervention',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='date_representant_intervenant_fin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='date_site_intervention',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nom_representant_intervenant1',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nom_representant_intervenant2',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nom_representant_intervenant_fin',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nom_site_intervention',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nom_site_intervention_fin',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='nombre_intervenant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='numero_urgence',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='responsable_intervention1',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='responsable_intervention2',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='responsable_intervention3',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='site_laisse_normale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='site_laisse_propre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='travail_non_termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='travail_temine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='checklist_stat',
            name='visa_site_intervention',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
