# Generated by Django 4.2.5 on 2023-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_checklist_permis_feu_prest_alerte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='user_profile',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
