# Generated by Django 4.2.5 on 2023-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_checklist_stat_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_espace_confine',
            name='user_profile_confine',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_excavation',
            name='user_profile_excavation',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='user_profile_feu',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
