# Generated by Django 4.2.5 on 2023-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_produit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Performance_sante',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='person',
            name='prenom',
        ),
        migrations.AddField(
            model_name='person',
            name='accident',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='poste_adapte',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='premier_secours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='presque_accident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='soins_medicaux',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
