# Generated by Django 4.2.5 on 2023-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_produit_performance_sante_remove_person_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_sante',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='performance_sante',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='performance_sante',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='person',
            name='accident',
        ),
        migrations.RemoveField(
            model_name='person',
            name='poste_adapte',
        ),
        migrations.RemoveField(
            model_name='person',
            name='premier_secours',
        ),
        migrations.RemoveField(
            model_name='person',
            name='presque_accident',
        ),
        migrations.RemoveField(
            model_name='person',
            name='soins_medicaux',
        ),
        migrations.AddField(
            model_name='performance_sante',
            name='accident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance_sante',
            name='poste_adapte',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance_sante',
            name='premier_secours',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance_sante',
            name='presque_accident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance_sante',
            name='soins_medicaux',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='nom',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='prenom',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
