# Generated by Django 4.2.5 on 2023-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_performance_sante_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_sante',
            name='name',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
