# Generated by Django 4.2.5 on 2023-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_performance_sante_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_sante',
            name='heure_travailler',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
