# Generated by Django 4.2.5 on 2023-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_performance_sante_heure_travailler'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_sante',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
