# Generated by Django 4.2.5 on 2023-10-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_performance_sante_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_sante',
            name='total',
        ),
    ]
