# Generated by Django 4.2.5 on 2023-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_performance_sante_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='arret_distribution_total',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='charge_station_service',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
