# Generated by Django 4.2.5 on 2023-10-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_checklist_stat_arret_distribution_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_jovena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('homme', models.PositiveBigIntegerField(default=0)),
                ('femme', models.PositiveBigIntegerField(default=0)),
                ('effectif_total_sur_site', models.PositiveBigIntegerField(default=0)),
                ('heure_travailler', models.PositiveBigIntegerField(default=0)),
                ('fatalite', models.PositiveBigIntegerField(default=0)),
                ('accident', models.PositiveBigIntegerField(default=0)),
                ('poste_adapte', models.PositiveBigIntegerField(default=0)),
                ('soins_medicaux', models.PositiveBigIntegerField(default=0)),
                ('premier_secours', models.PositiveBigIntegerField(default=0)),
                ('presque_accident', models.PositiveBigIntegerField(default=0)),
                ('dommage_materiel', models.PositiveBigIntegerField(default=0)),
                ('heure_perdue', models.PositiveBigIntegerField(default=0)),
                ('km_parcouru', models.PositiveBigIntegerField(default=0)),
                ('nombre_incident', models.PositiveBigIntegerField(default=0)),
                ('nombre_acceleration_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_freinage_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_depassement', models.PositiveBigIntegerField(default=0)),
                ('taux_frequence_incident', models.PositiveBigIntegerField(default=0)),
                ('taux_gravite_incident', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Performance_sante',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
