# Generated by Django 4.2.5 on 2023-10-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_kpi_jovena_delete_performance_sante_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_jovena',
            name='taux_frequence_incident',
        ),
        migrations.RemoveField(
            model_name='kpi_jovena',
            name='taux_gravite_incident',
        ),
    ]
