# Generated by Django 4.2.5 on 2023-10-24 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_kpi_jovena_taux_frequence_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_jovena',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='kpi_jovena',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi_jovena',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
