# Generated by Django 4.2.5 on 2023-10-24 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_kpi_jovena_date_kpi_jovena_taux_frequence_incident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('homme', models.PositiveBigIntegerField(default=0)),
                ('femme', models.PositiveBigIntegerField(default=0)),
                ('effectif_total_sur_site', models.PositiveBigIntegerField(default=0)),
                ('heure_travailler', models.PositiveBigIntegerField(default=0)),
                ('fatalite', models.PositiveBigIntegerField(default=0)),
                ('accident', models.PositiveBigIntegerField(default=0)),
                ('poste_adapte', models.PositiveBigIntegerField(default=0)),
                ('soins_medicaux', models.PositiveBigIntegerField(default=0)),
                ('premier_secours', models.PositiveBigIntegerField(default=0)),
                ('presque_accident', models.PositiveBigIntegerField(default=0)),
                ('dommage_materiel', models.PositiveBigIntegerField(default=0)),
                ('heure_perdue', models.PositiveBigIntegerField(default=0)),
                ('km_parcouru', models.PositiveBigIntegerField(default=0)),
                ('nombre_incident', models.PositiveBigIntegerField(default=0)),
                ('nombre_acceleration_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_freinage_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_depassement', models.PositiveBigIntegerField(default=0)),
                ('taux_frequence_incident', models.PositiveBigIntegerField(default=12)),
                ('taux_gravite_incident', models.PositiveBigIntegerField(default=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_station_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('homme', models.PositiveBigIntegerField(default=0)),
                ('femme', models.PositiveBigIntegerField(default=0)),
                ('effectif_total_sur_site', models.PositiveBigIntegerField(default=0)),
                ('heure_travailler', models.PositiveBigIntegerField(default=0)),
                ('fatalite', models.PositiveBigIntegerField(default=0)),
                ('accident', models.PositiveBigIntegerField(default=0)),
                ('poste_adapte', models.PositiveBigIntegerField(default=0)),
                ('soins_medicaux', models.PositiveBigIntegerField(default=0)),
                ('premier_secours', models.PositiveBigIntegerField(default=0)),
                ('presque_accident', models.PositiveBigIntegerField(default=0)),
                ('dommage_materiel', models.PositiveBigIntegerField(default=0)),
                ('heure_perdue', models.PositiveBigIntegerField(default=0)),
                ('km_parcouru', models.PositiveBigIntegerField(default=0)),
                ('nombre_incident', models.PositiveBigIntegerField(default=0)),
                ('nombre_acceleration_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_freinage_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_depassement', models.PositiveBigIntegerField(default=0)),
                ('taux_frequence_incident', models.PositiveBigIntegerField(default=12)),
                ('taux_gravite_incident', models.PositiveBigIntegerField(default=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('homme', models.PositiveBigIntegerField(default=0)),
                ('femme', models.PositiveBigIntegerField(default=0)),
                ('effectif_total_sur_site', models.PositiveBigIntegerField(default=0)),
                ('heure_travailler', models.PositiveBigIntegerField(default=0)),
                ('fatalite', models.PositiveBigIntegerField(default=0)),
                ('accident', models.PositiveBigIntegerField(default=0)),
                ('poste_adapte', models.PositiveBigIntegerField(default=0)),
                ('soins_medicaux', models.PositiveBigIntegerField(default=0)),
                ('premier_secours', models.PositiveBigIntegerField(default=0)),
                ('presque_accident', models.PositiveBigIntegerField(default=0)),
                ('dommage_materiel', models.PositiveBigIntegerField(default=0)),
                ('heure_perdue', models.PositiveBigIntegerField(default=0)),
                ('km_parcouru', models.PositiveBigIntegerField(default=0)),
                ('nombre_incident', models.PositiveBigIntegerField(default=0)),
                ('nombre_acceleration_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_freinage_brusque', models.PositiveBigIntegerField(default=0)),
                ('nombre_depassement', models.PositiveBigIntegerField(default=0)),
                ('taux_frequence_incident', models.PositiveBigIntegerField(default=12)),
                ('taux_gravite_incident', models.PositiveBigIntegerField(default=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='kpi_jovena',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='kpi_jovena',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=15),
        ),
    ]
