# Generated by Django 4.2.5 on 2023-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_kpi_prestataire_kpi_station_service_kpi_transporteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_jovena',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_jovena',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_prestataire',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_prestataire',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_station_service',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_station_service',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_transporteur',
            name='taux_frequence_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_transporteur',
            name='taux_gravite_incident',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
