# Generated by Django 4.2.5 on 2023-10-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_kpi_jovena_approvionnement_eau_potable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_transporteur',
            name='declarees',
        ),
        migrations.RemoveField(
            model_name='kpi_transporteur',
            name='herbegement_travailleurs',
        ),
        migrations.RemoveField(
            model_name='kpi_transporteur',
            name='parties_prenantes',
        ),
    ]
