# Generated by Django 4.2.5 on 2023-10-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_kpi_transporteur_declarees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_jovena',
            name='declarees',
        ),
        migrations.RemoveField(
            model_name='kpi_jovena',
            name='herbegement_travailleurs',
        ),
        migrations.RemoveField(
            model_name='kpi_jovena',
            name='parties_prenantes',
        ),
        migrations.RemoveField(
            model_name='kpi_prestataire',
            name='declarees',
        ),
        migrations.RemoveField(
            model_name='kpi_prestataire',
            name='herbegement_travailleurs',
        ),
        migrations.RemoveField(
            model_name='kpi_prestataire',
            name='parties_prenantes',
        ),
        migrations.RemoveField(
            model_name='kpi_station_service',
            name='declarees',
        ),
        migrations.RemoveField(
            model_name='kpi_station_service',
            name='herbegement_travailleurs',
        ),
        migrations.RemoveField(
            model_name='kpi_station_service',
            name='parties_prenantes',
        ),
    ]
