# Generated by Django 4.2.5 on 2023-10-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_checklist_espace_confinez_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist_espace_confinez',
            options={'verbose_name': 'Espace Confiner', 'verbose_name_plural': 'Espace Confiner'},
        ),
        migrations.AlterModelOptions(
            name='checklist_excavation',
            options={'verbose_name': 'Permis Excavation', 'verbose_name_plural': 'Permis Excavation'},
        ),
        migrations.AlterModelOptions(
            name='checklist_permis_feu_prest',
            options={'verbose_name': 'Permis Feu', 'verbose_name_plural': 'Permis Feu'},
        ),
        migrations.AlterModelOptions(
            name='checklist_stat',
            options={'verbose_name': 'Checklist Station', 'verbose_name_plural': 'Checklist Station'},
        ),
        migrations.AlterModelOptions(
            name='document_jov',
            options={'verbose_name': 'Document Jovena', 'verbose_name_plural': 'Documents Jovena'},
        ),
        migrations.AlterModelOptions(
            name='document_prest',
            options={'verbose_name': 'Document Prestataire', 'verbose_name_plural': 'Documents Prestataire'},
        ),
        migrations.AlterModelOptions(
            name='document_stat',
            options={'verbose_name': 'Document Station', 'verbose_name_plural': 'Documents Station'},
        ),
        migrations.AlterModelOptions(
            name='document_trans',
            options={'verbose_name': 'Document Transporteur', 'verbose_name_plural': 'Documents Transporteur'},
        ),
        migrations.AlterModelOptions(
            name='kpi_jovena',
            options={'verbose_name': 'KPI Jovena', 'verbose_name_plural': 'KPI Jovena'},
        ),
        migrations.AlterModelOptions(
            name='kpi_prestataire',
            options={'verbose_name': 'KPI Prestataire', 'verbose_name_plural': 'KPI Prestataire'},
        ),
        migrations.AlterModelOptions(
            name='kpi_station_service',
            options={'verbose_name': 'KPI Station', 'verbose_name_plural': 'KPI Station'},
        ),
        migrations.AlterModelOptions(
            name='kpi_transporteur',
            options={'verbose_name': 'KPI Transporteur', 'verbose_name_plural': 'KPI Transporteur'},
        ),
    ]
