# Generated by Django 4.2.5 on 2023-11-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_checklist_espace_confinez_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='validation',
        ),
    ]
