# Generated by Django 4.2.5 on 2023-11-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_checklist_permis_feu_prest_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='validation',
        ),
    ]
