# Generated by Django 4.2.5 on 2023-11-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_checklist_excavation_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_excavation',
            name='validation',
            field=models.CharField(choices=[('en_attente', 'En attente de réponse'), ('confirme', 'Confirmé'), ('refuse', 'Refusé')], default='en_attente', max_length=15),
        ),
    ]
