# Generated by Django 4.2.5 on 2023-11-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_checklist_excavation_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_excavation',
            name='validation',
        ),
    ]
