# Generated by Django 4.2.5 on 2023-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_checklist_excavation_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_poste',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
