# Generated by Django 4.2.5 on 2023-11-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_userprofile_id_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_poste',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
