# Generated by Django 4.2.5 on 2023-11-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_userprofile_id_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_stat',
            name='visa_site_intervention',
        ),
    ]
